services:
  db:
    image: postgres:16-alpine
    container_name: pawangcuaca_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pawangcuaca_db
      POSTGRES_USER: pawangcuaca_user
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pawangcuaca_user -d pawangcuaca_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
